// 由 scripts/gen-seed.mjs 从 docs/samplePrompt + migration.rs 常量生成，请勿手改。
// 重新生成：node scripts/gen-seed.mjs
export type SeedDimension = {
  id: string
  key: string
  nameCn: string
  nameEn: string
  sortOrder: number
  isMultiSelect: boolean
}

export type SeedModule = {
  id: string
  dimKey: string
  contentEn: string
  displayName: string
  isNsfw: boolean
  isEnabled: boolean
}

export type SeedRule = {
  id: string
  name: string
  type: string
  sourceDimensionId: string | null
  sourceModuleId: string | null
  targetDimensionId: string | null
  targetModuleId: string | null
  message: string
}

export const SEED_VERSION = 1

export const SEED_DIMENSIONS: SeedDimension[] = [
  { id: 'dim_01', key: 'body', nameCn: "模特身材特点", nameEn: 'Body', sortOrder: 4, isMultiSelect: false },
  { id: 'dim_02', key: 'face', nameCn: "模特面部特点", nameEn: 'Face', sortOrder: 5, isMultiSelect: false },
  { id: 'dim_03', key: 'top', nameCn: "模特上装", nameEn: 'Top', sortOrder: 6, isMultiSelect: false },
  { id: 'dim_04', key: 'bottom', nameCn: "模特下装", nameEn: 'Bottom', sortOrder: 7, isMultiSelect: false },
  { id: 'dim_05', key: 'outfit', nameCn: "模特全身套装", nameEn: 'Outfit', sortOrder: 8, isMultiSelect: false },
  { id: 'dim_06', key: 'shoes', nameCn: "模特鞋袜", nameEn: 'Shoes', sortOrder: 9, isMultiSelect: false },
  { id: 'dim_07', key: 'accessories', nameCn: "模特配饰", nameEn: 'Accessories', sortOrder: 10, isMultiSelect: true },
  { id: 'dim_08', key: 'pose', nameCn: "模特姿势", nameEn: 'Pose', sortOrder: 11, isMultiSelect: false },
  { id: 'dim_09', key: 'props', nameCn: "交互物品", nameEn: 'Props', sortOrder: 12, isMultiSelect: false },
  { id: 'dim_10', key: 'background', nameCn: "背景风格", nameEn: 'Background', sortOrder: 13, isMultiSelect: false },
  { id: 'dim_11', key: 'camera', nameCn: "相机参数", nameEn: 'Camera', sortOrder: 14, isMultiSelect: false },
  { id: 'dim_12', key: 'gender', nameCn: "模特性别", nameEn: 'Gender', sortOrder: 1, isMultiSelect: false },
  { id: 'dim_13', key: 'ethnicity', nameCn: "模特人种", nameEn: 'Ethnicity', sortOrder: 2, isMultiSelect: false },
  { id: 'dim_14', key: 'height', nameCn: "模特身高", nameEn: 'Height', sortOrder: 3, isMultiSelect: false },
]
export const SEED_MODULES: SeedModule[] = [
  { id: 'mod_body_01', dimKey: 'body', contentEn: "slim waist, long legs, hourglass figure", displayName: "slim waist, long legs, hourglass figure", isNsfw: false, isEnabled: true },
  { id: 'mod_body_02', dimKey: 'body', contentEn: "petite frame, delicate collarbones, slender arms", displayName: "petite frame, delicate collarbones, slender arms", isNsfw: false, isEnabled: true },
  { id: 'mod_body_03', dimKey: 'body', contentEn: "tall and athletic build, toned abs, long limbs", displayName: "tall and athletic build, toned abs, long limbs", isNsfw: false, isEnabled: true },
  { id: 'mod_body_04', dimKey: 'body', contentEn: "curvy figure, wide hips, generous bust, thick thighs", displayName: "curvy figure, wide hips, generous bust, thick thighs", isNsfw: false, isEnabled: true },
  { id: 'mod_body_05', dimKey: 'body', contentEn: "slim petite body, small waist, flat stomach", displayName: "slim petite body, small waist, flat stomach", isNsfw: false, isEnabled: true },
  { id: 'mod_body_06', dimKey: 'body', contentEn: "voluptuous body, large breasts, round hips, full figure", displayName: "voluptuous body, large breasts, round hips, full figure", isNsfw: false, isEnabled: true },
  { id: 'mod_body_07', dimKey: 'body', contentEn: "slender figure, graceful neck, elegant posture", displayName: "slender figure, graceful neck, elegant posture", isNsfw: false, isEnabled: true },
  { id: 'mod_body_08', dimKey: 'body', contentEn: "muscular physique, defined abs, strong shoulders", displayName: "muscular physique, defined abs, strong shoulders", isNsfw: false, isEnabled: true },
  { id: 'mod_body_09', dimKey: 'body', contentEn: "plus-size body, soft curves, full hips, generous proportions", displayName: "plus-size body, soft curves, full hips, generous proportions", isNsfw: false, isEnabled: true },
  { id: 'mod_body_10', dimKey: 'body', contentEn: "toned body, fit figure, athletic legs, sculpted arms", displayName: "toned body, fit figure, athletic legs, sculpted arms", isNsfw: false, isEnabled: true },
  { id: 'mod_body_11', dimKey: 'body', contentEn: "pear-shaped body, narrow shoulders, wide hips, thick thighs", displayName: "pear-shaped body, narrow shoulders, wide hips, thick thighs", isNsfw: false, isEnabled: true },
  { id: 'mod_body_12', dimKey: 'body', contentEn: "hourglass silhouette, cinched waist, proportional bust and hips", displayName: "hourglass silhouette, cinched waist, proportional bust and hips", isNsfw: false, isEnabled: true },
  { id: 'mod_body_13', dimKey: 'body', contentEn: "petite and busty, short stature, large chest, small waist", displayName: "petite and busty, short stature, large chest, small waist", isNsfw: false, isEnabled: true },
  { id: 'mod_body_14', dimKey: 'body', contentEn: "tall and slender, long legs, model proportions, slim build", displayName: "tall and slender, long legs, model proportions, slim build", isNsfw: false, isEnabled: true },
  { id: 'mod_body_15', dimKey: 'body', contentEn: "nude body, bare skin, soft natural curves, exposed figure", displayName: "nude body, bare skin, soft natural curves, exposed figure", isNsfw: true, isEnabled: true },
  { id: 'mod_body_16', dimKey: 'body', contentEn: "lean and lanky, narrow waist, elongated torso", displayName: "lean and lanky, narrow waist, elongated torso", isNsfw: false, isEnabled: true },
  { id: 'mod_body_17', dimKey: 'body', contentEn: "soft hourglass, gentle curves, balanced proportions", displayName: "soft hourglass, gentle curves, balanced proportions", isNsfw: false, isEnabled: true },
  { id: 'mod_body_18', dimKey: 'body', contentEn: "broad shoulders, tapered waist, athletic V-shape", displayName: "broad shoulders, tapered waist, athletic V-shape", isNsfw: false, isEnabled: true },
  { id: 'mod_body_19', dimKey: 'body', contentEn: "petite and delicate, small frame, fine boned", displayName: "petite and delicate, small frame, fine boned", isNsfw: false, isEnabled: true },
  { id: 'mod_body_20', dimKey: 'body', contentEn: "tall and statuesque, long neck, elegant limbs", displayName: "tall and statuesque, long neck, elegant limbs", isNsfw: false, isEnabled: true },
  { id: 'mod_body_21', dimKey: 'body', contentEn: "curvy and confident, full bust, rounded hips", displayName: "curvy and confident, full bust, rounded hips", isNsfw: false, isEnabled: true },
  { id: 'mod_body_22', dimKey: 'body', contentEn: "fit and toned, visible abs, strong core", displayName: "fit and toned, visible abs, strong core", isNsfw: false, isEnabled: true },
  { id: 'mod_body_23', dimKey: 'body', contentEn: "slender and willowy, graceful silhouette", displayName: "slender and willowy, graceful silhouette", isNsfw: false, isEnabled: true },
  { id: 'mod_body_24', dimKey: 'body', contentEn: "plus-size graceful, soft fullness, warm presence", displayName: "plus-size graceful, soft fullness, warm presence", isNsfw: false, isEnabled: true },
  { id: 'mod_body_25', dimKey: 'body', contentEn: "sun-kissed skin, athletic glow, healthy sheen", displayName: "sun-kissed skin, athletic glow, healthy sheen", isNsfw: false, isEnabled: true },
  { id: 'mod_body_26', dimKey: 'body', contentEn: "soft nude silhouette, smooth skin, natural curves, subtle shadow", displayName: "soft nude silhouette, smooth skin, natural curves, subtle shadow", isNsfw: true, isEnabled: true },
  { id: 'mod_body_27', dimKey: 'body', contentEn: "bare shoulders, smooth back, gentle body curve, soft lighting", displayName: "bare shoulders, smooth back, gentle body curve, soft lighting", isNsfw: true, isEnabled: true },
  { id: 'mod_body_28', dimKey: 'body', contentEn: "nude body, bare skin, exposed figure, soft intimate tones", displayName: "nude body, bare skin, exposed figure, soft intimate tones", isNsfw: true, isEnabled: true },
  { id: 'mod_face_01', dimKey: 'face', contentEn: "oval face, almond eyes, natural makeup", displayName: "oval face, almond eyes, natural makeup", isNsfw: false, isEnabled: true },
  { id: 'mod_face_02', dimKey: 'face', contentEn: "round face, big doe eyes, rosy cheeks, soft features", displayName: "round face, big doe eyes, rosy cheeks, soft features", isNsfw: false, isEnabled: true },
  { id: 'mod_face_03', dimKey: 'face', contentEn: "heart-shaped face, full lips, long eyelashes", displayName: "heart-shaped face, full lips, long eyelashes", isNsfw: false, isEnabled: true },
  { id: 'mod_face_04', dimKey: 'face', contentEn: "sharp jawline, high cheekbones, smokey eye makeup", displayName: "sharp jawline, high cheekbones, smokey eye makeup", isNsfw: false, isEnabled: true },
  { id: 'mod_face_05', dimKey: 'face', contentEn: "square face, strong brows, defined features", displayName: "square face, strong brows, defined features", isNsfw: false, isEnabled: true },
  { id: 'mod_face_06', dimKey: 'face', contentEn: "doll-like face, large round eyes, small nose, plump lips", displayName: "doll-like face, large round eyes, small nose, plump lips", isNsfw: false, isEnabled: true },
  { id: 'mod_face_07', dimKey: 'face', contentEn: "asian features, monolid eyes, straight black hair", displayName: "asian features, monolid eyes, straight black hair", isNsfw: false, isEnabled: true },
  { id: 'mod_face_08', dimKey: 'face', contentEn: "freckled face, green eyes, natural red hair, fair skin", displayName: "freckled face, green eyes, natural red hair, fair skin", isNsfw: false, isEnabled: true },
  { id: 'mod_face_09', dimKey: 'face', contentEn: "mature face, deep-set eyes, defined cheekbones, elegant look", displayName: "mature face, deep-set eyes, defined cheekbones, elegant look", isNsfw: false, isEnabled: true },
  { id: 'mod_face_10', dimKey: 'face', contentEn: "baby face, small features, youthful appearance, clear skin", displayName: "baby face, small features, youthful appearance, clear skin", isNsfw: false, isEnabled: true },
  { id: 'mod_face_11', dimKey: 'face', contentEn: "high bridge nose, full lips, blue eyes, blonde hair", displayName: "high bridge nose, full lips, blue eyes, blonde hair", isNsfw: false, isEnabled: true },
  { id: 'mod_face_12', dimKey: 'face', contentEn: "fox-like eyes, sharp brows, thin lips, angular face", displayName: "fox-like eyes, sharp brows, thin lips, angular face", isNsfw: false, isEnabled: true },
  { id: 'mod_face_13', dimKey: 'face', contentEn: "mixed race features, hazel eyes, curly brown hair, tan skin", displayName: "mixed race features, hazel eyes, curly brown hair, tan skin", isNsfw: false, isEnabled: true },
  { id: 'mod_face_14', dimKey: 'face', contentEn: "porcelain skin, straight nose, pink lips, straight black hair", displayName: "porcelain skin, straight nose, pink lips, straight black hair", isNsfw: false, isEnabled: true },
  { id: 'mod_face_15', dimKey: 'face', contentEn: "seductive expression, half-lidded eyes, parted glossy lips, flushed cheeks", displayName: "seductive expression, half-lidded eyes, parted glossy lips, flushed cheeks", isNsfw: true, isEnabled: true },
  { id: 'mod_face_16', dimKey: 'face', contentEn: "soft oval face, gentle smile, calm gaze", displayName: "soft oval face, gentle smile, calm gaze", isNsfw: false, isEnabled: true },
  { id: 'mod_face_17', dimKey: 'face', contentEn: "defined cheekbones, subtle contour, matte skin", displayName: "defined cheekbones, subtle contour, matte skin", isNsfw: false, isEnabled: true },
  { id: 'mod_face_18', dimKey: 'face', contentEn: "bright eyes, arched brows, lively expression", displayName: "bright eyes, arched brows, lively expression", isNsfw: false, isEnabled: true },
  { id: 'mod_face_19', dimKey: 'face', contentEn: "soft freckles, sun-kissed nose, natural glow", displayName: "soft freckles, sun-kissed nose, natural glow", isNsfw: false, isEnabled: true },
  { id: 'mod_face_20', dimKey: 'face', contentEn: "sharp cat eyes, bold eyeliner, confident stare", displayName: "sharp cat eyes, bold eyeliner, confident stare", isNsfw: false, isEnabled: true },
  { id: 'mod_face_21', dimKey: 'face', contentEn: "sweet smile, dimples, youthful cheeks", displayName: "sweet smile, dimples, youthful cheeks", isNsfw: false, isEnabled: true },
  { id: 'mod_face_22', dimKey: 'face', contentEn: "cool aloof face, pale skin, distant gaze", displayName: "cool aloof face, pale skin, distant gaze", isNsfw: false, isEnabled: true },
  { id: 'mod_face_23', dimKey: 'face', contentEn: "warm brown eyes, soft brows, approachable look", displayName: "warm brown eyes, soft brows, approachable look", isNsfw: false, isEnabled: true },
  { id: 'mod_face_24', dimKey: 'face', contentEn: "sculpted jaw, contour highlight, editorial makeup", displayName: "sculpted jaw, contour highlight, editorial makeup", isNsfw: false, isEnabled: true },
  { id: 'mod_face_25', dimKey: 'face', contentEn: "glowing skin, dewy finish, minimal makeup", displayName: "glowing skin, dewy finish, minimal makeup", isNsfw: false, isEnabled: true },
  { id: 'mod_face_26', dimKey: 'face', contentEn: "parted lips, flushed cheeks, half-lidded eyes, intimate gaze", displayName: "parted lips, flushed cheeks, half-lidded eyes, intimate gaze", isNsfw: true, isEnabled: true },
  { id: 'mod_face_27', dimKey: 'face', contentEn: "seductive smile, glossy lips, soft breath, close-up", displayName: "seductive smile, glossy lips, soft breath, close-up", isNsfw: true, isEnabled: true },
  { id: 'mod_face_28', dimKey: 'face', contentEn: "flushed face, parted glossy lips, heavy breathing, intimate expression", displayName: "flushed face, parted glossy lips, heavy breathing, intimate expression", isNsfw: true, isEnabled: true },
  { id: 'mod_top_01', dimKey: 'top', contentEn: "oversized white shirt, rolled sleeves", displayName: "oversized white shirt, rolled sleeves", isNsfw: false, isEnabled: true },
  { id: 'mod_top_02', dimKey: 'top', contentEn: "cropped knit cardigan, beige", displayName: "cropped knit cardigan, beige", isNsfw: false, isEnabled: true },
  { id: 'mod_top_03', dimKey: 'top', contentEn: "black silk camisole, lace trim", displayName: "black silk camisole, lace trim", isNsfw: false, isEnabled: true },
  { id: 'mod_top_04', dimKey: 'top', contentEn: "white cotton t-shirt, tucked in", displayName: "white cotton t-shirt, tucked in", isNsfw: false, isEnabled: true },
  { id: 'mod_top_05', dimKey: 'top', contentEn: "denim jacket, distressed details", displayName: "denim jacket, distressed details", isNsfw: false, isEnabled: true },
  { id: 'mod_top_06', dimKey: 'top', contentEn: "silk blouse, navy blue, buttoned up", displayName: "silk blouse, navy blue, buttoned up", isNsfw: false, isEnabled: true },
  { id: 'mod_top_07', dimKey: 'top', contentEn: "off-shoulder sweater, cream color", displayName: "off-shoulder sweater, cream color", isNsfw: false, isEnabled: true },
  { id: 'mod_top_08', dimKey: 'top', contentEn: "leather biker jacket, black, zipped", displayName: "leather biker jacket, black, zipped", isNsfw: false, isEnabled: true },
  { id: 'mod_top_09', dimKey: 'top', contentEn: "sheer mesh top, long sleeves", displayName: "sheer mesh top, long sleeves", isNsfw: false, isEnabled: true },
  { id: 'mod_top_10', dimKey: 'top', contentEn: "striped breton shirt, navy and white", displayName: "striped breton shirt, navy and white", isNsfw: false, isEnabled: true },
  { id: 'mod_top_11', dimKey: 'top', contentEn: "turtleneck sweater, cashmere, charcoal", displayName: "turtleneck sweater, cashmere, charcoal", isNsfw: false, isEnabled: true },
  { id: 'mod_top_12', dimKey: 'top', contentEn: "floral blouse, puff sleeves, pastel", displayName: "floral blouse, puff sleeves, pastel", isNsfw: false, isEnabled: true },
  { id: 'mod_top_13', dimKey: 'top', contentEn: "white tank top, ribbed cotton", displayName: "white tank top, ribbed cotton", isNsfw: false, isEnabled: true },
  { id: 'mod_top_14', dimKey: 'top', contentEn: "lace bralette, white, sheer overlay", displayName: "lace bralette, white, sheer overlay", isNsfw: false, isEnabled: true },
  { id: 'mod_top_15', dimKey: 'top', contentEn: "unbuttoned dress shirt, no bra, bare cleavage visible", displayName: "unbuttoned dress shirt, no bra, bare cleavage visible", isNsfw: true, isEnabled: true },
  { id: 'mod_top_16', dimKey: 'top', contentEn: "cropped denim jacket, light blue", displayName: "cropped denim jacket, light blue", isNsfw: false, isEnabled: true },
  { id: 'mod_top_17', dimKey: 'top', contentEn: "oversized hoodie, grey, kangaroo pocket", displayName: "oversized hoodie, grey, kangaroo pocket", isNsfw: false, isEnabled: true },
  { id: 'mod_top_18', dimKey: 'top', contentEn: "fitted ribbed knit top, cream", displayName: "fitted ribbed knit top, cream", isNsfw: false, isEnabled: true },
  { id: 'mod_top_19', dimKey: 'top', contentEn: "sleeveless linen blouse, beige", displayName: "sleeveless linen blouse, beige", isNsfw: false, isEnabled: true },
  { id: 'mod_top_20', dimKey: 'top', contentEn: "checkered flannel shirt, red and black", displayName: "checkered flannel shirt, red and black", isNsfw: false, isEnabled: true },
  { id: 'mod_top_21', dimKey: 'top', contentEn: "sheer chiffon blouse, floral print", displayName: "sheer chiffon blouse, floral print", isNsfw: false, isEnabled: true },
  { id: 'mod_top_22', dimKey: 'top', contentEn: "cropped tank with tie front, white", displayName: "cropped tank with tie front, white", isNsfw: false, isEnabled: true },
  { id: 'mod_top_23', dimKey: 'top', contentEn: "long sleeve henley, olive green", displayName: "long sleeve henley, olive green", isNsfw: false, isEnabled: true },
  { id: 'mod_top_24', dimKey: 'top', contentEn: "sequined crop top, silver", displayName: "sequined crop top, silver", isNsfw: false, isEnabled: true },
  { id: 'mod_top_25', dimKey: 'top', contentEn: "velvet camisole, deep burgundy", displayName: "velvet camisole, deep burgundy", isNsfw: false, isEnabled: true },
  { id: 'mod_top_26', dimKey: 'top', contentEn: "sheer lace top, visible bra underneath, soft translucence", displayName: "sheer lace top, visible bra underneath, soft translucence", isNsfw: true, isEnabled: true },
  { id: 'mod_top_27', dimKey: 'top', contentEn: "cropped top, underboob glimpse, thin fabric clinging", displayName: "cropped top, underboob glimpse, thin fabric clinging", isNsfw: true, isEnabled: true },
  { id: 'mod_top_28', dimKey: 'top', contentEn: "unbuttoned shirt, no bra, bare cleavage visible", displayName: "unbuttoned shirt, no bra, bare cleavage visible", isNsfw: true, isEnabled: true },
  { id: 'mod_bottom_01', dimKey: 'bottom', contentEn: "high-waisted pleated skirt, plaid", displayName: "high-waisted pleated skirt, plaid", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_02', dimKey: 'bottom', contentEn: "wide-leg jeans, light wash", displayName: "wide-leg jeans, light wash", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_03', dimKey: 'bottom', contentEn: "black leather mini skirt", displayName: "black leather mini skirt", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_04', dimKey: 'bottom', contentEn: "beige tailored trousers, straight leg", displayName: "beige tailored trousers, straight leg", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_05', dimKey: 'bottom', contentEn: "denim shorts, frayed hem", displayName: "denim shorts, frayed hem", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_06', dimKey: 'bottom', contentEn: "white linen wide-leg pants", displayName: "white linen wide-leg pants", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_07', dimKey: 'bottom', contentEn: "grey sweatpants, tapered fit", displayName: "grey sweatpants, tapered fit", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_08', dimKey: 'bottom', contentEn: "navy pleated midi skirt", displayName: "navy pleated midi skirt", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_09', dimKey: 'bottom', contentEn: "black skinny jeans, high rise", displayName: "black skinny jeans, high rise", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_10', dimKey: 'bottom', contentEn: "plaid A-line skirt, above knee", displayName: "plaid A-line skirt, above knee", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_11', dimKey: 'bottom', contentEn: "cargo pants, olive green, utility style", displayName: "cargo pants, olive green, utility style", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_12', dimKey: 'bottom', contentEn: "silk slip skirt, champagne color", displayName: "silk slip skirt, champagne color", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_13', dimKey: 'bottom', contentEn: "corduroy pants, brown, flare leg", displayName: "corduroy pants, brown, flare leg", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_14', dimKey: 'bottom', contentEn: "black denim cutoff shorts, very short", displayName: "black denim cutoff shorts, very short", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_15', dimKey: 'bottom', contentEn: "sheer lace panties, high-cut, visible through skirt slit", displayName: "sheer lace panties, high-cut, visible through skirt slit", isNsfw: true, isEnabled: true },
  { id: 'mod_bottom_16', dimKey: 'bottom', contentEn: "pleated tennis skirt, white", displayName: "pleated tennis skirt, white", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_17', dimKey: 'bottom', contentEn: "wide-leg cargo trousers, khaki", displayName: "wide-leg cargo trousers, khaki", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_18', dimKey: 'bottom', contentEn: "high-waisted skinny jeans, dark wash", displayName: "high-waisted skinny jeans, dark wash", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_19', dimKey: 'bottom', contentEn: "satin wide-leg pants, champagne", displayName: "satin wide-leg pants, champagne", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_20', dimKey: 'bottom', contentEn: "leather mini skirt, burgundy", displayName: "leather mini skirt, burgundy", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_21', dimKey: 'bottom', contentEn: "paperbag waist shorts, beige", displayName: "paperbag waist shorts, beige", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_22', dimKey: 'bottom', contentEn: "wool tailored trousers, charcoal", displayName: "wool tailored trousers, charcoal", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_23', dimKey: 'bottom', contentEn: "denim midi skirt, button front, blue", displayName: "denim midi skirt, button front, blue", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_24', dimKey: 'bottom', contentEn: "corduroy wide-leg pants, mustard", displayName: "corduroy wide-leg pants, mustard", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_25', dimKey: 'bottom', contentEn: "ruffled mini skirt, pink, layered", displayName: "ruffled mini skirt, pink, layered", isNsfw: false, isEnabled: true },
  { id: 'mod_bottom_26', dimKey: 'bottom', contentEn: "high slit skirt, lace underwear glimpse, thigh exposure", displayName: "high slit skirt, lace underwear glimpse, thigh exposure", isNsfw: true, isEnabled: true },
  { id: 'mod_bottom_27', dimKey: 'bottom', contentEn: "low-rise pants, hip curve, thin waistband, skin visible", displayName: "low-rise pants, hip curve, thin waistband, skin visible", isNsfw: true, isEnabled: true },
  { id: 'mod_bottom_28', dimKey: 'bottom', contentEn: "sheer lace panties, high-cut, visible through skirt slit", displayName: "sheer lace panties, high-cut, visible through skirt slit", isNsfw: true, isEnabled: true },
  { id: 'mod_outfit_01', dimKey: 'outfit', contentEn: "red bodycon dress, knee-length", displayName: "red bodycon dress, knee-length", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_02', dimKey: 'outfit', contentEn: "denim jumpsuit, sleeveless", displayName: "denim jumpsuit, sleeveless", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_03', dimKey: 'outfit', contentEn: "black slip dress, satin, midi length", displayName: "black slip dress, satin, midi length", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_04', dimKey: 'outfit', contentEn: "white linen shirt dress, belted", displayName: "white linen shirt dress, belted", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_05', dimKey: 'outfit', contentEn: "navy blue business suit, tailored", displayName: "navy blue business suit, tailored", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_06', dimKey: 'outfit', contentEn: "floral summer dress, spaghetti straps", displayName: "floral summer dress, spaghetti straps", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_07', dimKey: 'outfit', contentEn: "grey knitted sweater dress", displayName: "grey knitted sweater dress", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_08', dimKey: 'outfit', contentEn: "leather mini dress, black, form-fitting", displayName: "leather mini dress, black, form-fitting", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_09', dimKey: 'outfit', contentEn: "beige trench coat dress, double-breasted", displayName: "beige trench coat dress, double-breasted", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_10', dimKey: 'outfit', contentEn: "silk wrap dress, emerald green", displayName: "silk wrap dress, emerald green", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_11', dimKey: 'outfit', contentEn: "white cotton sundress, tiered", displayName: "white cotton sundress, tiered", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_12', dimKey: 'outfit', contentEn: "black turtleneck midi dress, ribbed knit", displayName: "black turtleneck midi dress, ribbed knit", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_13', dimKey: 'outfit', contentEn: "pink satin slip dress, cowl neckline", displayName: "pink satin slip dress, cowl neckline", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_14', dimKey: 'outfit', contentEn: "oversized denim overall dress", displayName: "oversized denim overall dress", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_15', dimKey: 'outfit', contentEn: "lingerie set, black lace bra and matching thong, garter belt with stockings", displayName: "lingerie set, black lace bra and matching thong, garter belt with stockings", isNsfw: true, isEnabled: true },
  { id: 'mod_outfit_16', dimKey: 'outfit', contentEn: "satin slip dress, champagne", displayName: "satin slip dress, champagne", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_17', dimKey: 'outfit', contentEn: "tailored jumpsuit, black, wide leg", displayName: "tailored jumpsuit, black, wide leg", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_18', dimKey: 'outfit', contentEn: "knit co-ord set, beige, lounge wear", displayName: "knit co-ord set, beige, lounge wear", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_19', dimKey: 'outfit', contentEn: "velvet evening gown, emerald", displayName: "velvet evening gown, emerald", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_20', dimKey: 'outfit', contentEn: "shirt dress, light blue, oversized", displayName: "shirt dress, light blue, oversized", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_21', dimKey: 'outfit', contentEn: "pleated midi dress, mustard yellow", displayName: "pleated midi dress, mustard yellow", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_22', dimKey: 'outfit', contentEn: "denim overall dress, light wash", displayName: "denim overall dress, light wash", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_23', dimKey: 'outfit', contentEn: "sequin party dress, gold", displayName: "sequin party dress, gold", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_24', dimKey: 'outfit', contentEn: "linen wrap dress, terracotta", displayName: "linen wrap dress, terracotta", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_25', dimKey: 'outfit', contentEn: "tweed dress with gold buttons, cream", displayName: "tweed dress with gold buttons, cream", isNsfw: false, isEnabled: true },
  { id: 'mod_outfit_26', dimKey: 'outfit', contentEn: "slip dress with deep neckline, satin clinging to body", displayName: "slip dress with deep neckline, satin clinging to body", isNsfw: true, isEnabled: true },
  { id: 'mod_outfit_27', dimKey: 'outfit', contentEn: "tight bodycon dress, sheer panels, curve hugging", displayName: "tight bodycon dress, sheer panels, curve hugging", isNsfw: true, isEnabled: true },
  { id: 'mod_outfit_28', dimKey: 'outfit', contentEn: "black lace lingerie set, bra and thong, garter belt", displayName: "black lace lingerie set, bra and thong, garter belt", isNsfw: true, isEnabled: true },
  { id: 'mod_shoes_01', dimKey: 'shoes', contentEn: "white sneakers, clean minimalist", displayName: "white sneakers, clean minimalist", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_02', dimKey: 'shoes', contentEn: "black over-knee socks, sheer", displayName: "black over-knee socks, sheer", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_03', dimKey: 'shoes', contentEn: "nude pointed-toe heels, stiletto", displayName: "nude pointed-toe heels, stiletto", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_04', dimKey: 'shoes', contentEn: "white ankle socks, frilled edge", displayName: "white ankle socks, frilled edge", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_05', dimKey: 'shoes', contentEn: "brown leather ankle boots, chunky heel", displayName: "brown leather ankle boots, chunky heel", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_06', dimKey: 'shoes', contentEn: "black patent leather loafers", displayName: "black patent leather loafers", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_07', dimKey: 'shoes', contentEn: "beige ballet flats, round toe", displayName: "beige ballet flats, round toe", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_08', dimKey: 'shoes', contentEn: "thigh-high black leather boots", displayName: "thigh-high black leather boots", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_09', dimKey: 'shoes', contentEn: "white canvas high-top sneakers", displayName: "white canvas high-top sneakers", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_10', dimKey: 'shoes', contentEn: "sheer black thigh-high stockings", displayName: "sheer black thigh-high stockings", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_11', dimKey: 'shoes', contentEn: "strappy sandals, nude, low heel", displayName: "strappy sandals, nude, low heel", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_12', dimKey: 'shoes', contentEn: "grey ribbed knee-high socks", displayName: "grey ribbed knee-high socks", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_13', dimKey: 'shoes', contentEn: "black platform boots, chunky sole", displayName: "black platform boots, chunky sole", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_14', dimKey: 'shoes', contentEn: "white fishnet thigh-high stockings", displayName: "white fishnet thigh-high stockings", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_15', dimKey: 'shoes', contentEn: "barefoot, soft clean soles, resting on tiptoes", displayName: "barefoot, soft clean soles, resting on tiptoes", isNsfw: true, isEnabled: true },
  { id: 'mod_shoes_16', dimKey: 'shoes', contentEn: "chunky loafers, black patent", displayName: "chunky loafers, black patent", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_17', dimKey: 'shoes', contentEn: "strappy block heels, nude", displayName: "strappy block heels, nude", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_18', dimKey: 'shoes', contentEn: "suede ankle boots, tan", displayName: "suede ankle boots, tan", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_19', dimKey: 'shoes', contentEn: "canvas slip-ons, white", displayName: "canvas slip-ons, white", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_20', dimKey: 'shoes', contentEn: "pointed toe kitten heels, black velvet", displayName: "pointed toe kitten heels, black velvet", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_21', dimKey: 'shoes', contentEn: "sport sandals, white and beige", displayName: "sport sandals, white and beige", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_22', dimKey: 'shoes', contentEn: "over-knee suede boots, grey", displayName: "over-knee suede boots, grey", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_23', dimKey: 'shoes', contentEn: "mary jane flats, black patent, strap", displayName: "mary jane flats, black patent, strap", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_24', dimKey: 'shoes', contentEn: "sock boots, white, stretch knit", displayName: "sock boots, white, stretch knit", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_25', dimKey: 'shoes', contentEn: "leather oxford shoes, brown brogue", displayName: "leather oxford shoes, brown brogue", isNsfw: false, isEnabled: true },
  { id: 'mod_shoes_26', dimKey: 'shoes', contentEn: "bare legs with garter stockings, strap details", displayName: "bare legs with garter stockings, strap details", isNsfw: true, isEnabled: true },
  { id: 'mod_shoes_27', dimKey: 'shoes', contentEn: "thigh-high stockings, lace top, skin contrast", displayName: "thigh-high stockings, lace top, skin contrast", isNsfw: true, isEnabled: true },
  { id: 'mod_shoes_28', dimKey: 'shoes', contentEn: "barefoot, soft soles, intimate foot focus, delicate", displayName: "barefoot, soft soles, intimate foot focus, delicate", isNsfw: true, isEnabled: true },
  { id: 'mod_accessories_01', dimKey: 'accessories', contentEn: "gold hoop earrings, mini shoulder bag", displayName: "gold hoop earrings, mini shoulder bag", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_02', dimKey: 'accessories', contentEn: "silver pendant necklace, round sunglasses", displayName: "silver pendant necklace, round sunglasses", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_03', dimKey: 'accessories', contentEn: "pearl stud earrings, leather watch", displayName: "pearl stud earrings, leather watch", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_04', dimKey: 'accessories', contentEn: "black wide-brim hat, oversized frame glasses", displayName: "black wide-brim hat, oversized frame glasses", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_05', dimKey: 'accessories', contentEn: "gold chain necklace, stacked rings", displayName: "gold chain necklace, stacked rings", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_06', dimKey: 'accessories', contentEn: "silk hair scarf, cat-eye sunglasses", displayName: "silk hair scarf, cat-eye sunglasses", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_07', dimKey: 'accessories', contentEn: "leather belt, gold buckle, minimal", displayName: "leather belt, gold buckle, minimal", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_08', dimKey: 'accessories', contentEn: "canvas tote bag, striped pattern", displayName: "canvas tote bag, striped pattern", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_09', dimKey: 'accessories', contentEn: "silver ear cuffs, geometric design", displayName: "silver ear cuffs, geometric design", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_10', dimKey: 'accessories', contentEn: "gold bangle bracelets, stacked", displayName: "gold bangle bracelets, stacked", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_11', dimKey: 'accessories', contentEn: "mini backpack, quilted leather", displayName: "mini backpack, quilted leather", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_12', dimKey: 'accessories', contentEn: "wire-rimmed reading glasses, gold frame", displayName: "wire-rimmed reading glasses, gold frame", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_13', dimKey: 'accessories', contentEn: "silk scrunchie, oversized, cream", displayName: "silk scrunchie, oversized, cream", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_14', dimKey: 'accessories', contentEn: "chunky resin ring, statement earrings", displayName: "chunky resin ring, statement earrings", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_15', dimKey: 'accessories', contentEn: "delicate body chain draped across bare collarbones", displayName: "delicate body chain draped across bare collarbones", isNsfw: true, isEnabled: true },
  { id: 'mod_accessories_16', dimKey: 'accessories', contentEn: "pearl choker, vintage", displayName: "pearl choker, vintage", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_17', dimKey: 'accessories', contentEn: "gold hoop earrings, oversized", displayName: "gold hoop earrings, oversized", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_18', dimKey: 'accessories', contentEn: "silk headband, wide, pastel", displayName: "silk headband, wide, pastel", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_19', dimKey: 'accessories', contentEn: "leather crossbody bag, tan", displayName: "leather crossbody bag, tan", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_20', dimKey: 'accessories', contentEn: "chunky gold chain necklace, layered", displayName: "chunky gold chain necklace, layered", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_21', dimKey: 'accessories', contentEn: "small rectangular sunglasses, black", displayName: "small rectangular sunglasses, black", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_22', dimKey: 'accessories', contentEn: "beaded clutch, colorful", displayName: "beaded clutch, colorful", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_23', dimKey: 'accessories', contentEn: "thin leather belt, brown, minimal", displayName: "thin leather belt, brown, minimal", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_24', dimKey: 'accessories', contentEn: "crystal hair clips, set of two", displayName: "crystal hair clips, set of two", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_25', dimKey: 'accessories', contentEn: "wool beret, camel", displayName: "wool beret, camel", isNsfw: false, isEnabled: true },
  { id: 'mod_accessories_26', dimKey: 'accessories', contentEn: "thin chain across bare back, delicate intimate jewelry", displayName: "thin chain across bare back, delicate intimate jewelry", isNsfw: true, isEnabled: true },
  { id: 'mod_accessories_27', dimKey: 'accessories', contentEn: "body chain draped across bare collarbones", displayName: "body chain draped across bare collarbones", isNsfw: true, isEnabled: true },
  { id: 'mod_accessories_28', dimKey: 'accessories', contentEn: "lace choker with ribbon, intimate accessory, close-up", displayName: "lace choker with ribbon, intimate accessory, close-up", isNsfw: true, isEnabled: true },
  { id: 'mod_pose_01', dimKey: 'pose', contentEn: "standing with hands in pockets", displayName: "standing with hands in pockets", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_02', dimKey: 'pose', contentEn: "sitting sideways, legs crossed", displayName: "sitting sideways, legs crossed", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_03', dimKey: 'pose', contentEn: "leaning against wall, arms crossed", displayName: "leaning against wall, arms crossed", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_04', dimKey: 'pose', contentEn: "walking towards camera, natural stride", displayName: "walking towards camera, natural stride", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_05', dimKey: 'pose', contentEn: "sitting on chair, leaning forward", displayName: "sitting on chair, leaning forward", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_06', dimKey: 'pose', contentEn: "standing, one hand on hip, head tilted", displayName: "standing, one hand on hip, head tilted", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_07', dimKey: 'pose', contentEn: "crouching down, resting on heels", displayName: "crouching down, resting on heels", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_08', dimKey: 'pose', contentEn: "looking over shoulder, half body turn", displayName: "looking over shoulder, half body turn", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_09', dimKey: 'pose', contentEn: "standing contrapposto, relaxed", displayName: "standing contrapposto, relaxed", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_10', dimKey: 'pose', contentEn: "sitting on floor, knees pulled up", displayName: "sitting on floor, knees pulled up", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_11', dimKey: 'pose', contentEn: "stretching arms overhead, back arched", displayName: "stretching arms overhead, back arched", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_12', dimKey: 'pose', contentEn: "kneeling on one knee, hands on thighs", displayName: "kneeling on one knee, hands on thighs", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_13', dimKey: 'pose', contentEn: "sitting on edge of table, legs dangling", displayName: "sitting on edge of table, legs dangling", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_14', dimKey: 'pose', contentEn: "standing profile, looking away", displayName: "standing profile, looking away", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_15', dimKey: 'pose', contentEn: "lying on back, arms above head, legs slightly apart, arched back", displayName: "lying on back, arms above head, legs slightly apart, arched back", isNsfw: true, isEnabled: true },
  { id: 'mod_pose_16', dimKey: 'pose', contentEn: "walking stride, mid-step, natural swing", displayName: "walking stride, mid-step, natural swing", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_17', dimKey: 'pose', contentEn: "seated with legs crossed, hands on lap", displayName: "seated with legs crossed, hands on lap", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_18', dimKey: 'pose', contentEn: "leaning forward, elbows on knees", displayName: "leaning forward, elbows on knees", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_19', dimKey: 'pose', contentEn: "standing with arms crossed, confident", displayName: "standing with arms crossed, confident", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_20', dimKey: 'pose', contentEn: "sitting on stool, one leg extended", displayName: "sitting on stool, one leg extended", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_21', dimKey: 'pose', contentEn: "looking back over shoulder, walking away", displayName: "looking back over shoulder, walking away", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_22', dimKey: 'pose', contentEn: "hands behind back, standing straight", displayName: "hands behind back, standing straight", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_23', dimKey: 'pose', contentEn: "crouching, arms resting on knees", displayName: "crouching, arms resting on knees", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_24', dimKey: 'pose', contentEn: "reclining on sofa, relaxed", displayName: "reclining on sofa, relaxed", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_25', dimKey: 'pose', contentEn: "jumping mid-air, dynamic motion", displayName: "jumping mid-air, dynamic motion", isNsfw: false, isEnabled: true },
  { id: 'mod_pose_26', dimKey: 'pose', contentEn: "reclining on bed, one knee up, soft arched back", displayName: "reclining on bed, one knee up, soft arched back", isNsfw: true, isEnabled: true },
  { id: 'mod_pose_27', dimKey: 'pose', contentEn: "lying on side, legs slightly apart, hand on hip", displayName: "lying on side, legs slightly apart, hand on hip", isNsfw: true, isEnabled: true },
  { id: 'mod_pose_28', dimKey: 'pose', contentEn: "lying on back, arms above head, legs apart, arched back", displayName: "lying on back, arms above head, legs apart, arched back", isNsfw: true, isEnabled: true },
  { id: 'mod_props_01', dimKey: 'props', contentEn: "holding coffee cup", displayName: "holding coffee cup", isNsfw: false, isEnabled: true },
  { id: 'mod_props_02', dimKey: 'props', contentEn: "leaning on railing", displayName: "leaning on railing", isNsfw: false, isEnabled: true },
  { id: 'mod_props_03', dimKey: 'props', contentEn: "holding open book", displayName: "holding open book", isNsfw: false, isEnabled: true },
  { id: 'mod_props_04', dimKey: 'props', contentEn: "carrying shopping bags", displayName: "carrying shopping bags", isNsfw: false, isEnabled: true },
  { id: 'mod_props_05', dimKey: 'props', contentEn: "holding smartphone to ear", displayName: "holding smartphone to ear", isNsfw: false, isEnabled: true },
  { id: 'mod_props_06', dimKey: 'props', contentEn: "holding bouquet of flowers", displayName: "holding bouquet of flowers", isNsfw: false, isEnabled: true },
  { id: 'mod_props_07', dimKey: 'props', contentEn: "leaning on umbrella, closed", displayName: "leaning on umbrella, closed", isNsfw: false, isEnabled: true },
  { id: 'mod_props_08', dimKey: 'props', contentEn: "holding glass of wine", displayName: "holding glass of wine", isNsfw: false, isEnabled: true },
  { id: 'mod_props_09', dimKey: 'props', contentEn: "holding leather handbag", displayName: "holding leather handbag", isNsfw: false, isEnabled: true },
  { id: 'mod_props_10', dimKey: 'props', contentEn: "playing with phone in hand", displayName: "playing with phone in hand", isNsfw: false, isEnabled: true },
  { id: 'mod_props_11', dimKey: 'props', contentEn: "holding a pen, writing in notebook", displayName: "holding a pen, writing in notebook", isNsfw: false, isEnabled: true },
  { id: 'mod_props_12', dimKey: 'props', contentEn: "resting chin on folded hands", displayName: "resting chin on folded hands", isNsfw: false, isEnabled: true },
  { id: 'mod_props_13', dimKey: 'props', contentEn: "holding small mirror, checking reflection", displayName: "holding small mirror, checking reflection", isNsfw: false, isEnabled: true },
  { id: 'mod_props_14', dimKey: 'props', contentEn: "twirling a keychain around finger", displayName: "twirling a keychain around finger", isNsfw: false, isEnabled: true },
  { id: 'mod_props_15', dimKey: 'props', contentEn: "holding a silk robe, partially covering body", displayName: "holding a silk robe, partially covering body", isNsfw: true, isEnabled: true },
  { id: 'mod_props_16', dimKey: 'props', contentEn: "holding book, open pages", displayName: "holding book, open pages", isNsfw: false, isEnabled: true },
  { id: 'mod_props_17', dimKey: 'props', contentEn: "carrying tote bag, canvas", displayName: "carrying tote bag, canvas", isNsfw: false, isEnabled: true },
  { id: 'mod_props_18', dimKey: 'props', contentEn: "holding coffee, taking sip", displayName: "holding coffee, taking sip", isNsfw: false, isEnabled: true },
  { id: 'mod_props_19', dimKey: 'props', contentEn: "holding phone, selfie pose", displayName: "holding phone, selfie pose", isNsfw: false, isEnabled: true },
  { id: 'mod_props_20', dimKey: 'props', contentEn: "holding umbrella, open overhead", displayName: "holding umbrella, open overhead", isNsfw: false, isEnabled: true },
  { id: 'mod_props_21', dimKey: 'props', contentEn: "holding vinyl record, retro", displayName: "holding vinyl record, retro", isNsfw: false, isEnabled: true },
  { id: 'mod_props_22', dimKey: 'props', contentEn: "holding flower bouquet, casual", displayName: "holding flower bouquet, casual", isNsfw: false, isEnabled: true },
  { id: 'mod_props_23', dimKey: 'props', contentEn: "holding laptop, working", displayName: "holding laptop, working", isNsfw: false, isEnabled: true },
  { id: 'mod_props_24', dimKey: 'props', contentEn: "holding sunglasses, by temple", displayName: "holding sunglasses, by temple", isNsfw: false, isEnabled: true },
  { id: 'mod_props_25', dimKey: 'props', contentEn: "holding skateboard, urban", displayName: "holding skateboard, urban", isNsfw: false, isEnabled: true },
  { id: 'mod_props_26', dimKey: 'props', contentEn: "holding sheer fabric over body, partially draped", displayName: "holding sheer fabric over body, partially draped", isNsfw: true, isEnabled: true },
  { id: 'mod_props_27', dimKey: 'props', contentEn: "holding silk robe, slipping off shoulder", displayName: "holding silk robe, slipping off shoulder", isNsfw: true, isEnabled: true },
  { id: 'mod_props_28', dimKey: 'props', contentEn: "holding silk robe, partially covering body, bare skin visible", displayName: "holding silk robe, partially covering body, bare skin visible", isNsfw: true, isEnabled: true },
  { id: 'mod_background_01', dimKey: 'background', contentEn: "minimalist studio, white backdrop", displayName: "minimalist studio, white backdrop", isNsfw: false, isEnabled: true },
  { id: 'mod_background_02', dimKey: 'background', contentEn: "cherry blossom street, spring", displayName: "cherry blossom street, spring", isNsfw: false, isEnabled: true },
  { id: 'mod_background_03', dimKey: 'background', contentEn: "urban alley, neon signs, night", displayName: "urban alley, neon signs, night", isNsfw: false, isEnabled: true },
  { id: 'mod_background_04', dimKey: 'background', contentEn: "cozy cafe interior, warm lighting", displayName: "cozy cafe interior, warm lighting", isNsfw: false, isEnabled: true },
  { id: 'mod_background_05', dimKey: 'background', contentEn: "sandy beach, golden hour sunset", displayName: "sandy beach, golden hour sunset", isNsfw: false, isEnabled: true },
  { id: 'mod_background_06', dimKey: 'background', contentEn: "old European cobblestone street", displayName: "old European cobblestone street", isNsfw: false, isEnabled: true },
  { id: 'mod_background_07', dimKey: 'background', contentEn: "modern office, glass windows", displayName: "modern office, glass windows", isNsfw: false, isEnabled: true },
  { id: 'mod_background_08', dimKey: 'background', contentEn: "lush botanical garden, greenery", displayName: "lush botanical garden, greenery", isNsfw: false, isEnabled: true },
  { id: 'mod_background_09', dimKey: 'background', contentEn: "rooftop terrace, city skyline", displayName: "rooftop terrace, city skyline", isNsfw: false, isEnabled: true },
  { id: 'mod_background_10', dimKey: 'background', contentEn: "bedroom with soft curtains, morning light", displayName: "bedroom with soft curtains, morning light", isNsfw: false, isEnabled: true },
  { id: 'mod_background_11', dimKey: 'background', contentEn: "rainy street, reflections, moody", displayName: "rainy street, reflections, moody", isNsfw: false, isEnabled: true },
  { id: 'mod_background_12', dimKey: 'background', contentEn: "vintage library, bookshelves", displayName: "vintage library, bookshelves", isNsfw: false, isEnabled: true },
  { id: 'mod_background_13', dimKey: 'background', contentEn: "white sandy desert, clear sky", displayName: "white sandy desert, clear sky", isNsfw: false, isEnabled: true },
  { id: 'mod_background_14', dimKey: 'background', contentEn: "busy Tokyo crossing, crowd", displayName: "busy Tokyo crossing, crowd", isNsfw: false, isEnabled: true },
  { id: 'mod_background_15', dimKey: 'background', contentEn: "dimly lit hotel room, rumpled white sheets, warm lamp glow", displayName: "dimly lit hotel room, rumpled white sheets, warm lamp glow", isNsfw: true, isEnabled: true },
  { id: 'mod_background_16', dimKey: 'background', contentEn: "cozy bookstore, warm wood shelves", displayName: "cozy bookstore, warm wood shelves", isNsfw: false, isEnabled: true },
  { id: 'mod_background_17', dimKey: 'background', contentEn: "minimalist loft, concrete walls", displayName: "minimalist loft, concrete walls", isNsfw: false, isEnabled: true },
  { id: 'mod_background_18', dimKey: 'background', contentEn: "seaside pier, wooden planks", displayName: "seaside pier, wooden planks", isNsfw: false, isEnabled: true },
  { id: 'mod_background_19', dimKey: 'background', contentEn: "autumn forest, golden leaves", displayName: "autumn forest, golden leaves", isNsfw: false, isEnabled: true },
  { id: 'mod_background_20', dimKey: 'background', contentEn: "city street at dusk, street lights", displayName: "city street at dusk, street lights", isNsfw: false, isEnabled: true },
  { id: 'mod_background_21', dimKey: 'background', contentEn: "rooftop garden, potted plants", displayName: "rooftop garden, potted plants", isNsfw: false, isEnabled: true },
  { id: 'mod_background_22', dimKey: 'background', contentEn: "vintage diner, neon lights", displayName: "vintage diner, neon lights", isNsfw: false, isEnabled: true },
  { id: 'mod_background_23', dimKey: 'background', contentEn: "snow-covered street, winter", displayName: "snow-covered street, winter", isNsfw: false, isEnabled: true },
  { id: 'mod_background_24', dimKey: 'background', contentEn: "art gallery, white walls", displayName: "art gallery, white walls", isNsfw: false, isEnabled: true },
  { id: 'mod_background_25', dimKey: 'background', contentEn: "industrial warehouse, brick walls", displayName: "industrial warehouse, brick walls", isNsfw: false, isEnabled: true },
  { id: 'mod_background_26', dimKey: 'background', contentEn: "private bedroom, dim warm light, rumpled bedding", displayName: "private bedroom, dim warm light, rumpled bedding", isNsfw: true, isEnabled: true },
  { id: 'mod_background_27', dimKey: 'background', contentEn: "dim hotel room, soft lamp, intimate atmosphere", displayName: "dim hotel room, soft lamp, intimate atmosphere", isNsfw: true, isEnabled: true },
  { id: 'mod_background_28', dimKey: 'background', contentEn: "dimly lit hotel room, rumpled white sheets, warm lamp glow", displayName: "dimly lit hotel room, rumpled white sheets, warm lamp glow", isNsfw: true, isEnabled: true },
  { id: 'mod_camera_01', dimKey: 'camera', contentEn: "85mm lens, shallow depth of field, soft lighting", displayName: "85mm lens, shallow depth of field, soft lighting", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_02', dimKey: 'camera', contentEn: "50mm portrait, natural daylight, f/1.8", displayName: "50mm portrait, natural daylight, f/1.8", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_03', dimKey: 'camera', contentEn: "35mm wide angle, environmental portrait", displayName: "35mm wide angle, environmental portrait", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_04', dimKey: 'camera', contentEn: "135mm telephoto, blurred background, f/2.0", displayName: "135mm telephoto, blurred background, f/2.0", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_05', dimKey: 'camera', contentEn: "24mm, dramatic low angle, cinematic", displayName: "24mm, dramatic low angle, cinematic", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_06', dimKey: 'camera', contentEn: "macro lens, extreme close-up, ring light", displayName: "macro lens, extreme close-up, ring light", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_07', dimKey: 'camera', contentEn: "85mm, golden hour backlight, lens flare", displayName: "85mm, golden hour backlight, lens flare", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_08', dimKey: 'camera', contentEn: "70mm, studio softbox, even lighting", displayName: "70mm, studio softbox, even lighting", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_09', dimKey: 'camera', contentEn: "100mm, beauty lighting, smooth skin rendition", displayName: "100mm, beauty lighting, smooth skin rendition", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_10', dimKey: 'camera', contentEn: "28mm, candid street photography style", displayName: "28mm, candid street photography style", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_11', dimKey: 'camera', contentEn: "85mm, rim lighting, dark background", displayName: "85mm, rim lighting, dark background", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_12', dimKey: 'camera', contentEn: "50mm, window light, soft shadows", displayName: "50mm, window light, soft shadows", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_13', dimKey: 'camera', contentEn: "135mm, high key, overexposed background", displayName: "135mm, high key, overexposed background", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_14', dimKey: 'camera', contentEn: "35mm, film grain, vintage color grade", displayName: "35mm, film grain, vintage color grade", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_15', dimKey: 'camera', contentEn: "85mm, boudoir lighting, candlelit glow, warm intimate tones", displayName: "85mm, boudoir lighting, candlelit glow, warm intimate tones", isNsfw: true, isEnabled: true },
  { id: 'mod_camera_16', dimKey: 'camera', contentEn: "50mm, eye-level, shallow DOF, bokeh", displayName: "50mm, eye-level, shallow DOF, bokeh", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_17', dimKey: 'camera', contentEn: "35mm, top-down view, flat lay", displayName: "35mm, top-down view, flat lay", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_18', dimKey: 'camera', contentEn: "85mm, close-up, eye focus", displayName: "85mm, close-up, eye focus", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_19', dimKey: 'camera', contentEn: "24mm, wide panorama, dramatic sky", displayName: "24mm, wide panorama, dramatic sky", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_20', dimKey: 'camera', contentEn: "70mm, side lighting, soft shadows", displayName: "70mm, side lighting, soft shadows", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_21', dimKey: 'camera', contentEn: "100mm macro, detail texture", displayName: "100mm macro, detail texture", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_22', dimKey: 'camera', contentEn: "28mm, dutch angle, dynamic", displayName: "28mm, dutch angle, dynamic", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_23', dimKey: 'camera', contentEn: "85mm, natural window light, soft", displayName: "85mm, natural window light, soft", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_24', dimKey: 'camera', contentEn: "50mm, night mode, city lights bokeh", displayName: "50mm, night mode, city lights bokeh", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_25', dimKey: 'camera', contentEn: "lens flare, golden hour, backlit silhouette", displayName: "lens flare, golden hour, backlit silhouette", isNsfw: false, isEnabled: true },
  { id: 'mod_camera_26', dimKey: 'camera', contentEn: "close-up intimate lighting, soft focus, warm skin tones", displayName: "close-up intimate lighting, soft focus, warm skin tones", isNsfw: true, isEnabled: true },
  { id: 'mod_camera_27', dimKey: 'camera', contentEn: "shallow depth, skin detail, soft bokeh, intimate framing", displayName: "shallow depth, skin detail, soft bokeh, intimate framing", isNsfw: true, isEnabled: true },
  { id: 'mod_camera_28', dimKey: 'camera', contentEn: "boudoir lighting, candlelit glow, warm intimate tones", displayName: "boudoir lighting, candlelit glow, warm intimate tones", isNsfw: true, isEnabled: true },
  { id: 'mod_gender_01', dimKey: 'gender', contentEn: "female model, feminine presentation", displayName: "female model, feminine presentation", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_02', dimKey: 'gender', contentEn: "male model, masculine presentation", displayName: "male model, masculine presentation", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_03', dimKey: 'gender', contentEn: "female model, soft feminine, gentle makeup, delicate features", displayName: "female model, soft feminine, gentle makeup, delicate features", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_04', dimKey: 'gender', contentEn: "female model, natural feminine, casual styling, effortless look", displayName: "female model, natural feminine, casual styling, effortless look", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_05', dimKey: 'gender', contentEn: "female model, tomboyish feminine, short hair, cool casual", displayName: "female model, tomboyish feminine, short hair, cool casual", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_06', dimKey: 'gender', contentEn: "male model, soft masculine, clean features, gentle expression", displayName: "male model, soft masculine, clean features, gentle expression", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_07', dimKey: 'gender', contentEn: "male model, natural masculine, confident posture, relaxed fit", displayName: "male model, natural masculine, confident posture, relaxed fit", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_08', dimKey: 'gender', contentEn: "male model, refined masculine, tailored suit, sharp lines", displayName: "male model, refined masculine, tailored suit, sharp lines", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_09', dimKey: 'gender', contentEn: "neutral model, minimal gender cues, simple styling", displayName: "neutral model, minimal gender cues, simple styling", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_10', dimKey: 'gender', contentEn: "female model, elegant feminine, soft smile, graceful posture", displayName: "female model, elegant feminine, soft smile, graceful posture", isNsfw: false, isEnabled: true },
  { id: 'mod_gender_11', dimKey: 'gender', contentEn: "tomboy style, short hair, casual cool", displayName: "tomboy style, short hair, casual cool", isNsfw: false, isEnabled: false },
  { id: 'mod_gender_12', dimKey: 'gender', contentEn: "soft butch, tailored suit, understated", displayName: "soft butch, tailored suit, understated", isNsfw: false, isEnabled: false },
  { id: 'mod_gender_13', dimKey: 'gender', contentEn: "high femme, glamorous makeup, elegant", displayName: "high femme, glamorous makeup, elegant", isNsfw: false, isEnabled: false },
  { id: 'mod_gender_14', dimKey: 'gender', contentEn: "neutral model, minimal gender cues", displayName: "neutral model, minimal gender cues", isNsfw: false, isEnabled: false },
  { id: 'mod_gender_15', dimKey: 'gender', contentEn: "androgynous nude portrait, bare shoulders", displayName: "androgynous nude portrait, bare shoulders", isNsfw: false, isEnabled: false },
  { id: 'mod_ethnicity_01', dimKey: 'ethnicity', contentEn: "East Asian features, straight black hair, fair skin", displayName: "East Asian features, straight black hair, fair skin", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_02', dimKey: 'ethnicity', contentEn: "South Asian features, warm brown skin, dark eyes", displayName: "South Asian features, warm brown skin, dark eyes", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_03', dimKey: 'ethnicity', contentEn: "Southeast Asian features, tan skin, soft features", displayName: "Southeast Asian features, tan skin, soft features", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_04', dimKey: 'ethnicity', contentEn: "European features, light skin, blue eyes", displayName: "European features, light skin, blue eyes", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_05', dimKey: 'ethnicity', contentEn: "West African features, deep brown skin, coily hair", displayName: "West African features, deep brown skin, coily hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_06', dimKey: 'ethnicity', contentEn: "East African features, tall, slender, warm skin", displayName: "East African features, tall, slender, warm skin", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_07', dimKey: 'ethnicity', contentEn: "Middle Eastern features, olive skin, dark hair", displayName: "Middle Eastern features, olive skin, dark hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_08', dimKey: 'ethnicity', contentEn: "Latin American features, warm beige skin, wavy hair", displayName: "Latin American features, warm beige skin, wavy hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_09', dimKey: 'ethnicity', contentEn: "Mixed heritage, light tan skin, hazel eyes", displayName: "Mixed heritage, light tan skin, hazel eyes", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_10', dimKey: 'ethnicity', contentEn: "Central Asian features, light olive skin, almond eyes", displayName: "Central Asian features, light olive skin, almond eyes", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_11', dimKey: 'ethnicity', contentEn: "Pacific Islander features, warm brown skin, curly hair", displayName: "Pacific Islander features, warm brown skin, curly hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_12', dimKey: 'ethnicity', contentEn: "Nordic features, very fair skin, blonde hair", displayName: "Nordic features, very fair skin, blonde hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_13', dimKey: 'ethnicity', contentEn: "Mediterranean features, olive skin, dark wavy hair", displayName: "Mediterranean features, olive skin, dark wavy hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_14', dimKey: 'ethnicity', contentEn: "Afro-Caribbean features, rich brown skin, braided hair", displayName: "Afro-Caribbean features, rich brown skin, braided hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_15', dimKey: 'ethnicity', contentEn: "ambiguous ethnicity, sun-kissed skin, natural glow", displayName: "ambiguous ethnicity, sun-kissed skin, natural glow", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_16', dimKey: 'ethnicity', contentEn: "Han Chinese features, straight black hair, light to natural skin, balanced facial proportions", displayName: "Han Chinese features, straight black hair, light to natural skin, balanced facial proportions", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_17', dimKey: 'ethnicity', contentEn: "Zhuang ethnicity features, warm natural skin, soft facial features, dark hair", displayName: "Zhuang ethnicity features, warm natural skin, soft facial features, dark hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_18', dimKey: 'ethnicity', contentEn: "Uyghur features, Central Asian appearance, light olive skin, deep-set eyes, dark wavy hair", displayName: "Uyghur features, Central Asian appearance, light olive skin, deep-set eyes, dark wavy hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_19', dimKey: 'ethnicity', contentEn: "Hui ethnicity features, balanced East Asian appearance, natural skin, modest styling", displayName: "Hui ethnicity features, balanced East Asian appearance, natural skin, modest styling", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_20', dimKey: 'ethnicity', contentEn: "Manchu heritage, fair skin, straight black hair, soft East Asian features", displayName: "Manchu heritage, fair skin, straight black hair, soft East Asian features", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_21', dimKey: 'ethnicity', contentEn: "Miao ethnicity features, warm skin tone, expressive eyes, dark hair with subtle highlight", displayName: "Miao ethnicity features, warm skin tone, expressive eyes, dark hair with subtle highlight", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_22', dimKey: 'ethnicity', contentEn: "Yi ethnicity features, warm brown skin, defined cheekbones, dark hair", displayName: "Yi ethnicity features, warm brown skin, defined cheekbones, dark hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_23', dimKey: 'ethnicity', contentEn: "Tibetan features, highland appearance, warm sun-kissed skin, strong brows, dark hair", displayName: "Tibetan features, highland appearance, warm sun-kissed skin, strong brows, dark hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_24', dimKey: 'ethnicity', contentEn: "Mongolian features, warm beige skin, broad facial structure, dark hair", displayName: "Mongolian features, warm beige skin, broad facial structure, dark hair", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_25', dimKey: 'ethnicity', contentEn: "Dong ethnicity features, natural East Asian appearance, soft skin tone", displayName: "Dong ethnicity features, natural East Asian appearance, soft skin tone", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_26', dimKey: 'ethnicity', contentEn: "Chaoxianzu Korean-Chinese features, fair skin, soft East Asian features, neat styling", displayName: "Chaoxianzu Korean-Chinese features, fair skin, soft East Asian features, neat styling", isNsfw: false, isEnabled: true },
  { id: 'mod_ethnicity_27', dimKey: 'ethnicity', contentEn: "Dai ethnicity features, Southeast Asian appearance, warm tan skin, gentle features", displayName: "Dai ethnicity features, Southeast Asian appearance, warm tan skin, gentle features", isNsfw: false, isEnabled: true },
  { id: 'mod_height_01', dimKey: 'height', contentEn: "height 135cm, very petite, short stature, delicate frame", displayName: "height 135cm, very petite, short stature, delicate frame", isNsfw: false, isEnabled: true },
  { id: 'mod_height_02', dimKey: 'height', contentEn: "height 150cm, petite, compact proportions", displayName: "height 150cm, petite, compact proportions", isNsfw: false, isEnabled: true },
  { id: 'mod_height_03', dimKey: 'height', contentEn: "height 160cm, average height, balanced proportions", displayName: "height 160cm, average height, balanced proportions", isNsfw: false, isEnabled: true },
  { id: 'mod_height_04', dimKey: 'height', contentEn: "height 170cm, tall, elegant long legs", displayName: "height 170cm, tall, elegant long legs", isNsfw: false, isEnabled: true },
  { id: 'mod_height_05', dimKey: 'height', contentEn: "height 180cm, very tall, model height, statuesque", displayName: "height 180cm, very tall, model height, statuesque", isNsfw: false, isEnabled: true },
  { id: 'mod_height_06', dimKey: 'height', contentEn: "height 190cm, extremely tall, runway model, towering", displayName: "height 190cm, extremely tall, runway model, towering", isNsfw: false, isEnabled: true },
]
export const SEED_RULES: SeedRule[] = [
  { id: 'rule_01', name: '套装互斥', type: 'mutex', sourceDimensionId: 'dim_05', sourceModuleId: null, targetDimensionId: 'dim_03', targetModuleId: null, message: '已选全身套装，上装/下装将自动忽略' },
  { id: 'rule_02', name: '鞋袜与赤脚互斥', type: 'mutex', sourceDimensionId: 'dim_06', sourceModuleId: 'mod_shoes_15', targetDimensionId: 'dim_06', targetModuleId: null, message: '赤脚与鞋袜不可共存' },
  { id: 'rule_03', name: '室内外背景互斥', type: 'excludes', sourceDimensionId: 'dim_10', sourceModuleId: 'mod_bg_01', targetDimensionId: 'dim_10', targetModuleId: null, message: '室内背景与户外背景冲突' },
]
